/**
 * app.asar に差し込む shim の index.js を生成する。
 *
 * 連鎖の順序には理由がある（実測に基づく）:
 *  - Vencord の patcher.ts は最終行で `require(require.main.filename)` を実行し、
 *    Discord 本体をブートし切る。したがって Vencord より後ろに置いた patcher は
 *    メインウィンドウが作られた後にしか走れず、preload の登録が間に合わない。
 *    VoiceCord は必ず先に require する。
 *  - VoiceCord の patcher は Discord 本体をブートしない。ブートは Vencord か、
 *    Vencord が居なければ末尾の冪等ブートが行う。
 *  - 末尾の require(main) は保険。Node の require キャッシュは絶対パスで引くので、
 *    Vencord が正常にブート済みなら no-op になり、Vencord が途中で throw した
 *    場合はここが Discord を救済する。
 */

/** shim であることを見分けるためのマーカー。判定はこの文字列の有無で行う。 */
export const SHIM_MARKER = 'VoiceCord chain shim v1'

/** shim の package.json。Discord 本体と同じ app 名を名乗る必要がある。 */
export const SHIM_PACKAGE_JSON = '{"name":"discord","main":"index.js"}'

/**
 * 連鎖リストから shim の index.js を生成する。
 * @param chain require する patcher の絶対パス。先頭から順に require される。
 */
export function renderShimSource(chain: readonly string[]): string {
  // JSON.stringify で Windows のバックスラッシュを正しくエスケープする。
  const chainLiteral = JSON.stringify(chain)
  return `"use strict";
// ${SHIM_MARKER} ---- generated by VoiceCord, do not edit ----
var path = require("path"), fs = require("fs");
var CHAIN = ${chainLiteral};
for (var i = 0; i < CHAIN.length; i++) {
  try { if (fs.existsSync(CHAIN[i])) require(CHAIN[i]); }
  catch (e) { console.error("[VoiceCord shim] chain entry failed:", CHAIN[i], e); }
}
try {
  var injector = require.main.filename;
  var asar = path.join(path.dirname(injector), "..",
    require.main.path.endsWith("app.asar") ? "_app.asar" : "app.asar");
  var main = path.join(asar, require(path.join(asar, "package.json")).main);
  require.main.filename = main;
  require("electron").app.setAppPath(asar);
  require(main);
} catch (e) { console.error("[VoiceCord shim] boot failed:", e); }
`
}

/**
 * shim の index.js から連鎖リストを読み出す。
 * VoiceCord が書いた shim でなければ null を返す（他 mod の shim を壊さないため）。
 */
export function parseShimChain(source: string): string[] | null {
  if (!source.includes(SHIM_MARKER)) return null
  const m = /var CHAIN = (\[[^\]]*\]);/.exec(source)
  if (!m || m[1] === undefined) return null
  try {
    const parsed: unknown = JSON.parse(m[1])
    if (!Array.isArray(parsed) || !parsed.every((x) => typeof x === 'string')) return null
    return parsed as string[]
  } catch {
    return null
  }
}
